import { Navbar } from "@/components/navbar";
import type { Metadata } from "next";
import { Georama } from "next/font/google";
import "./globals.css";

const georama = Georama({
  subsets: ["latin"],
  variable: "--font-georama",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={georama.variable}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
